packages:
  - slides/
  - spikes/*

allowUnusedPatches: true

autoInstallPeers: false

dedupeInjectedDeps: true

dedupePeerDependents: true

peersSuffixMaxLength: 40

resolutionMode: highest

sharedWorkspaceLockfile: false
